openapi: 3.0.3
info:
  title: City Events Event Service
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Local Dev (Docker)
  - url: http://localhost:8080
    description: CI Default
paths:
  /healthz:
    get:
      summary: Health Check
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: OK

  /event/v1/events:
    get:
      summary: List Public Events (Feed)
      description: Returns a cursor-paginated list of published events. Supports FTS and category filtering.
      tags: [Public]
      parameters:
        - name: page_size
          in: query
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          description: "Sort order: start_time (default), created_at, relevance (if q present)"
          schema:
            type: string
            enum: [start_time, created_at, relevance]
        - name: cursor
          in: query
          description: Opaque cursor from previous response `next_cursor`.
          schema:
            type: string
        - name: q
          in: query
          description: Search term (FTS)
          schema:
            type: string
        - name: city
          in: query
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
        - name: from
          in: query
          description: Start time range (RFC3339)
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: End time range (RFC3339)
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResp_EventResp'

    post:
      summary: Create Event
      tags: [Organizer]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventReq'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataEnvelope_EventResp'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'

  /event/v1/events/{event_id}:
    get:
      summary: Get Event Details (Public)
      tags: [Public]
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataEnvelope_EventResp'
        404:
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update Event
      tags: [Organizer]
      security:
        - BearerAuth: []
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventReq'
      responses:
        200:
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataEnvelope_EventResp'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'

  /event/v1/events/{event_id}/publish:
    post:
      summary: Publish Event
      tags: [Organizer]
      security:
        - BearerAuth: []
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Published
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataEnvelope_EventResp'
        409:
          $ref: '#/components/responses/Conflict'

  /event/v1/events/{event_id}/cancel:
    post:
      summary: Cancel Event
      tags: [Organizer]
      security:
        - BearerAuth: []
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Canceled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataEnvelope_EventResp'
        409:
          $ref: '#/components/responses/Conflict'

  /event/v1/organizer/events:
    get:
      summary: List My Events
      description: List events created by the authenticated organizer
      tags: [Organizer]
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResp_EventResp'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # Requests
    CreateEventReq:
      type: object
      required: [title, description, city, category, start_time, end_time, capacity]
      properties:
        title:
          type: string
        description:
          type: string
        city:
          type: string
        category:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        capacity:
          type: integer
          minimum: 0

    UpdateEventReq:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        city:
          type: string
        category:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        capacity:
          type: integer
          minimum: 0

    # Responses
    EventResp:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        city:
          type: string
        category:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        capacity:
          type: integer
        status:
          type: string
          enum: [published, cancelled, draft]
        organizer_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    DataEnvelope_EventResp:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/EventResp'
        error:
          type: object
          nullable: true

    PageResp_EventResp:
      type: object
      properties:
        data:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/EventResp'
            total:
              type: integer
            page:
              type: integer
            page_size:
              type: integer
            next_cursor:
              type: string
              nullable: true

    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            meta:
              type: object

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict (e.g. State Transition)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
